#!/usr/bin/env python
#
# Script to build the files found in this directory.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper(env);
rootlibs  = env['ROOTLIBS']

mainlib = helper.make_mainlib ( [ 'mu2e_DbService',
                                  'mu2e_DbTables',
                                  'mu2e_GeneralUtilities',
                                  'cetlib',
                                  'cetlib_except',
                                  'pq',
                                  rootlibs ] )

helper.make_plugins( [ mainlib,
                       'mu2e_DataProducts',
                       'mu2e_RecoDataProducts',
                       'mu2e_MCDataProducts',
                       'mu2e_GeometryService',
                       'mu2e_CalorimeterGeom',
                       'mu2e_CaloCluster',
                       'KinKal_Trajectory',
                       'KinKal_General',
                       'mu2e_GeneralUtilities',
                       'art_Framework_Core',
                       'art_Framework_Principal',
                       'art_Persistency_Common',
                       'art_Persistency_Provenance',
                       'art_Utilities',
                       'canvas',
                       'fhiclcpp',
                       'fhiclcpp_types',
                       'tbb',
                       'cetlib',
                       'cetlib_except',
                       'boost_filesystem',
                       'boost_system',
                       'art_Framework_Services_Registry',
                       'art_root_io_tfile_support',
                       'art_root_io_TFileService',
                       rootlibs
                     ] )


helper.make_bin("dqmTool",[ mainlib,
                            'dqm',
                            'mu2e_DbService',
                            'mu2e_DbTables',
                            'mu2e_GeneralUtilities',
                            'boost_program_options',
                            'cetlib',
                            'cetlib_except',
                            'pq' ])

helper.make_bin("dqmMetrics",[ mainlib, rootlibs ] )

## turn pywrap.i into a python interface
helper.make_pywrap (['dqm','mu2e_DbService','mu2e_DbTables'])

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
